version: "3.6"
services:
  traefik:
    image: registry.bamilo.com/traefik:1.6-alpine
    networks:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: traefik-0.0.1
        target: /etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1'
          memory: 1G
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:traefik.localhost"
      restart_policy:
        condition: on-failure

configs:
  traefik-0.0.1:
    file: ./traefik.toml

networks:
  gateway:
    driver: overlay
    external: true
